### ISSUE TITLE
Highlight related nodes and relationships

### ISSUE THREAD

**Issue by bigluck** [kuzudb/explorer#99]
When exploring a new graph, it can sometimes be helpful to run a very generic query like `MATCH (a)—[r]—(b) RETURN a, r, b` and examine the relationships between the different nodes on the graph.

When I select a Node in the graph, the node properties panel is shown on the right, and the node itself is highlighted; but it does not help me to understand the relationships the selected node has with other nodes, especially if the graph is complex (and the UI overlap some relationships).

I'd love if all the other objects on the graph become opaque once a node is selected, except for the direct relationships and nodes linked to the selected node.

I think it will make it easier to visually analyze a graph.

**Comment by bigluck** [comment]
G6 seems to have built-in support for it:
http://g6-v3-2.antv.vision/en/examples/interaction/highlight

**Comment by mewim** [comment]
It seems that other graph visualization software such as Neo4j Browser and NebulaGraph Studio does not do that by default. I'll let @prrao87 and @semihsalihoglu-uw comment if this should be enabled by default or activated via a button / settings option.

**Comment by prrao87** [comment]
Hmm, I'm not sure that should be the default behaviour as a lot of users won't want to visually explore the graph this way (for example, they may just want to observe larger substructures). I'm pretty sure the reason that this isn't default behaviour in other packages is because visual graph exploration is treated as a specific use case and that the more general use case is a smooth UX that renders the nodes and edges efficiently (no lags) while allowing users to see how their data is connected at a high level.

Maybe what @mewim mentioned makes sense: Have a button with an "i" logo that's named "interactive highlight" that can enable/disable this behaviour, but I'd suggest that we avoid making this default behaviour.

**Comment by mewim** [comment]
@bigluck I implemented this:

<img width="2032" alt="Screenshot 2024-03-18 at 10 52 49 PM" src="https://github.com/kuzudb/explorer/assets/14037726/e78f13d7-1676-41c6-a85b-5c6ba1d85f49">

**Comment by bigluck** [comment]
Thanks @mewim
